# Compile Controller
FROM golang:1.11 as builder

COPY . $GOPATH/src/mypackage/myapp
WORKDIR $GOPATH/src/mypackage/myapp
RUN go get -d -v ./...
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -o /go/bin/credhub-controller . 

# Build small Controller Container
FROM scratch

COPY --from=builder /go/bin/credhub-controller /go/bin/credhub-controller
ENTRYPOINT ["/go/bin/credhub-controller"]