# Compile Controller
FROM golang:1.11 as builder

COPY . $GOPATH/src/github.com/oskoss/kubernetes-credhub/credhub-controller/
WORKDIR $GOPATH/src/github.com/oskoss/kubernetes-credhub/credhub-controller/
RUN go get -u github.com/UnnoTed/fileb0x && \
go generate && go get -d -v ./... && \
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -o /go/bin/credhub-controller . 

# Build small Controller Container
FROM scratch

COPY --from=builder /go/bin/credhub-controller /go/bin/credhub-controller
ENTRYPOINT ["/go/bin/credhub-controller"]