{{- if .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "credhub.fullname" . }}
  labels:
    app: {{ template "credhub.name" . }}
    chart: {{ template "credhub.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}
