apiVersion: v1
kind: Secret
metadata:
  name: {{ template "uaa.fullname" . }}
  labels:
    app: {{ template "uaa.name" . }}
    chart: {{ template "uaa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.credhub.password  }}
  credhubPassword: {{ .Values.credhub.password | b64enc | quote  }}
  {{ else }}
  credhubPassword: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.credhub.clientSecret  }}
  credhubClientSecret: {{ .Values.credhub.clientSecret | b64enc | quote  }}
  {{ else }}                                                                                                                   
  credhubClientSecret: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }} 
