# Compile Init
FROM golang:1.11 as builder

COPY . $GOPATH/src/mypackage/myapp
WORKDIR $GOPATH/src/mypackage/myapp
RUN go get -d -v ./...
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build  -o /go/bin/credhub-init . 

# Build small Init Container
FROM scratch

COPY --from=builder /go/bin/credhub-init /go/bin/credhub-init
EXPOSE 8080
ENTRYPOINT ["/go/bin/credhub-init"]

