apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        credhub.pivotal.io: "enable"
      labels:
        app:  example-app
    spec:
      containers:
      - name:  example-app
        image: oskoss/kubernetes-credhub-example-app:v0
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:  
  name: example-app
spec:
  selector:    
    app: example-app
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080